application: sectxtweb
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

#- url: /images
  #static_dir: /static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: sectxtweb.py

